# Structure format:
# main:
#   stratagem: "KEY_*"

# Example format:
# main:
#   reload: "KEY_P"
#   reinforce: "KEY_Y"

# View available Stratagems in the README

main:
  reload: "KEY_P"
  reinforce: "KEY_N"
  resupply: "KEY_M"
