# Structure format:
# main:
#   stratagem: "KEY_*"

# Example format:
# main:
#   reload: "KEY_P"
#   reinforce: "KEY_Y"

# View available Stratagems below the configuration

main:
  reload: "KEY_P"
  reinforce: "KEY_N"
  resupply: "KEY_M"

# Available Stratagems:
# reload: Hot-reload the configuration file
