from evdev import ecodes as e

stratagem_dict: dict[str, list[e]] = {
  # General
  "reinforce": [e.KEY_W, e.KEY_S, e.KEY_D, e.KEY_A, e.KEY_W],
  "resupply": [e.KEY_S, e.KEY_S, e.KEY_W, e.KEY_D],
  "sos": [e.KEY_W, e.KEY_S, e.KEY_D, e.KEY_W],
  "hellbomb": [e.KEY_S, e.KEY_W, e.KEY_A, e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_S, e.KEY_W],
  "flare": [e.KEY_D, e.KEY_D, e.KEY_A, e.KEY_A],
  "flag": [e.KEY_S, e.KEY_W, e.KEY_S, e.KEY_W],
  "seaf": [e.KEY_D, e.KEY_W, e.KEY_W, e.KEY_S],
  # Patriotic Administration Center
  "machine": [e.KEY_S, e.KEY_A, e.KEY_S, e.KEY_W, e.KEY_D],
  "antimaterial": [e.KEY_S, e.KEY_A, e.KEY_D, e.KEY_W, e.KEY_S],
  "stalwart": [e.KEY_S, e.KEY_A, e.KEY_S, e.KEY_W, e.KEY_W, e.KEY_A],
  "expendable": [e.KEY_S, e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_D],
  "recoilless": [e.KEY_S, e.KEY_A, e.KEY_D, e.KEY_D, e.KEY_A],
  "flamethrower": [e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_S, e.KEY_W],
  "autocannon": [e.KEY_S, e.KEY_A, e.KEY_S, e.KEY_W, e.KEY_W, e.KEY_D],
  "railgun": [e.KEY_S, e.KEY_D, e.KEY_S, e.KEY_W, e.KEY_A, e.KEY_D],
  "spear": [e.KEY_S, e.KEY_S, e.KEY_W, e.KEY_S, e.KEY_S],
  # Orbital Cannons
  "orbital_gatling": [e.KEY_D, e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_W],
  "orbital_airburst": [e.KEY_D, e.KEY_D, e.KEY_D],
  "orbital_120mm": [e.KEY_D, e.KEY_D, e.KEY_S, e.KEY_A, e.KEY_D, e.KEY_S],
  "orbital_380mm": [e.KEY_D, e.KEY_S, e.KEY_W, e.KEY_W, e.KEY_A,e.KEY_S, e.KEY_S],
  "orbital_walking": [e.KEY_D, e.KEY_D, e.KEY_S, e.KEY_A, e.KEY_D, e.KEY_S],
  "orbital_laser": [e.KEY_D, e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_S],
  "orbital_railcannon": [e.KEY_D, e.KEY_W, e.KEY_S, e.KEY_S, e.KEY_D],
  # Hangar
  "eagle_rearm": [e.KEY_W, e.KEY_W, e.KEY_A, e.KEY_W, e.KEY_D],
  "eagle_strafing": [e.KEY_W, e.KEY_D, e.KEY_D],
  "eagle_airstrike": [e.KEY_W, e.KEY_D, e.KEY_S, e.KEY_D],
  "eagle_cluster": [e.KEY_W, e.KEY_D, e.KEY_S, e.KEY_S, e.KEY_D],
  "eagle_napalm": [e.KEY_W, e.KEY_D, e.KEY_S, e.KEY_W],
  "jump_pack": [e.KEY_S, e.KEY_W, e.KEY_W, e.KEY_S, e.KEY_W],
  "eagle_smoke": [e.KEY_W, e.KEY_D, e.KEY_W, e.KEY_S],
  "eagle_110mm": [e.KEY_W, e.KEY_D, e.KEY_W, e.KEY_A],
  "eagle_500kg": [e.KEY_W, e.KEY_D, e.KEY_S, e.KEY_S, e.KEY_S],
  # Bridge
  "orbital_precision": [e.KEY_D, e.KEY_D, e.KEY_W],
  "orbital_gas": [e.KEY_D, e.KEY_D, e.KEY_S, e.KEY_D],
  "orbital_ems": [e.KEY_D, e.KEY_D, e.KEY_A, e.KEY_S],
  "orbital_smoke": [e.KEY_D, e.KEY_D, e.KEY_S, e.KEY_W],
  "hmg_replacement": [e.KEY_W, e.KEY_S, e.KEY_A, e.KEY_D, e.KEY_D, e.KEY_A],
  "shield_relay": [e.KEY_S, e.KEY_W, e.KEY_A, e.KEY_D, e.KEY_A, e.KEY_S],
  "tesla_tower": [e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_W, e.KEY_A, e.KEY_D],
  # Engineering Bay
  "minefield": [e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_D],
  "supply_pack": [e.KEY_S, e.KEY_A, e.KEY_S, e.KEY_W, e.KEY_W, e.KEY_S],
  "grenade_launcher": [e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_A, e.KEY_S],
  "laser_cannon": [e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_A, e.KEY_S],
  "incendiary_mines": [e.KEY_S, e.KEY_A, e.KEY_A, e.KEY_S],
  "guard_dog_rover": [e.KEY_S, e.KEY_A, e.KEY_S, e.KEY_W, e.KEY_A, e.KEY_S, e.KEY_S],
  "ballistic_shield": [e.KEY_S, e.KEY_A, e.KEY_W, e.KEY_W, e.KEY_D],
  "arc_thrower": [e.KEY_S, e.KEY_D, e.KEY_W, e.KEY_A, e.KEY_S],
  "shield_generator": [e.KEY_S, e.KEY_W, e.KEY_A, e.KEY_D, e.KEY_A, e.KEY_D],
  # Robotics Workshop
  "machine_sentry": [e.KEY_S,e.KEY_W, e.KEY_D, e.KEY_S, e.KEY_D, e.KEY_S, e.KEY_W],
  "gatling_sentry": [e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_A],
  "mortar_sentry": [e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_D, e.KEY_S],
  "guard_dog": [e.KEY_S, e.KEY_W, e.KEY_A, e.KEY_W, e.KEY_D, e.KEY_S],
  "autocannon_sentry": [e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_W, e.KEY_A, e.KEY_W],
  "rocket_sentry": [e.KEY_S, e.KEY_W, e.KEY_D, e.KEY_D, e.KEY_A],
  "ems_sentry": [e.KEY_S, e.KEY_S, e.KEY_W, e.KEY_W, e.KEY_A],
}
